const rooms = [
    {
        id:1,
        title:'prayaas girls hostel',
        location:'Dayal Bagh, Agra',
        accomodationFor:'Girls',
        suitableFor:'Students and Working',
        price:3000,
        image:['https://www.pgchoice.com/uploads/property/small/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
                'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
                'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Rajani Verma',
        description:'Located in Dayal Bagh, Agra, Prayaas Girls Hostel is modern and spacious PG home is close to major educational commercial hubs in the area. This female PG offers all the comforts like Wi-Fi etc. The PG has strict adherence to hygiene standards and offers double, triple rooms. Please contact in case you are interested or queries. Looking forward to serving you.',
        uploaded:'4 months ago'
    },
    {
        id:2,
        title:'jai villa',
        location:'Tora, Agra',
        accomodationFor:'Boys and Girls',
        suitableFor:'Students and Working',
        price:5500,
        image:['https://www.pgchoice.com/uploads/property/small/IMG_20210123_132451.webp',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Amit Sengar',
        description:'Located in Tora, Agra, Jai Villa is modern and spacious PG home is close to major educational commercial hubs in the area.',
        uploaded:'10 months ago'
    },
    {
        id:3,
        title:'Akash inn',
        location:'Sikandra, Agra',
        accomodationFor:'Boys',
        suitableFor:'Students and Working',
        price:7500,
        image:['https://www.pgchoice.com/uploads/property/small/aakash_inn_building_front__01.webp'
    ,'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
    'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Priyanshi Jain',
        uploaded:'11 months ago',
        description:'Located in Sikandra, Agra, Akash Inn is modern and spacious PG home is close to major educational commercial hubs in the area.'
    },
    {
        id:4,
        title:'Friends guest house and hostel',
        location:'Tejganj, Agra',
        accomodationFor:'Boys and Girls',
        suitableFor:'Working',
        price:6500,
        image:['https://www.pgchoice.com/uploads/property/small/PG_Agra.webp',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Friends guest house',
        uploaded:'3 months ago',
        description:'Located in Tejganj, Agra, Friends guest house and hostel is modern and spacious PG home is close to major educational commercial hubs in the area.'
    },
    {
        id:5,
        title:'celestia girls pg',
        location:'Navrangpura, Ahmedabad',
        accomodationFor:'Girls',
        suitableFor:'Students',
        price:9000,
        image:['https://www.pgchoice.com/uploads/property/small/Celestia_girls_pg_Single_Room.webp',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Celestia girls',
        uploaded:'6 months ago',
        description:'Located in Navrangpura, Ahmedabad, Semi furnished attached bathroom with kitchen tile flooring located at near jp palace hotel behind pearls resort fatehabad Road agra.'  
    },
    {
        id:6,
        title:'Sanskaar pg and hostel',
        location:'Sardar patel nagar, Ahmedabad',
        accomodationFor:'Boys and Girls',
        suitableFor:'Working',
        price:7500,
        image:['https://www.pgchoice.com/uploads/property/small/Sanskar_pg_and_hostel_9974097933_tworbed_sharing_room.webp',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Sanskaar pg',
        uploaded:'6 months ago',
        description:'Located in Sardar patel nagar, Ahmedabad, Sanskaar pg and hostel is modern and spacious PG home is close to major educational commercial hubs in the area.'
    },
    {
        id:7,
        title:'Royal pg',
        location:'Usmanpura, Ahmedabad',
        accomodationFor:'Boys and Girls',
        suitableFor:'Students',
        price:7000,
        image:['https://www.pgchoice.com/uploads/property/small/Royal_pg_in_Usmanpura_9924835783_twobed_sharing_room.webp',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Royal pg',
        uploaded:'6 months ago',
        description:'Located in Usmanpura, Ahmedabad, Royal pg is modern and spacious PG home is close to major educational commercial hubs in the area.'
    },  
    {
        id:8,
        title:'dozo iris premium girls pg',
        location:'Sector 1 hsr layout, Bangalore',
        accomodationFor:'Girls',
        suitableFor:'Students and Working',
        price:7500,
        image:['https://www.pgchoice.com/uploads/property/small/Front2.jpeg',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Chetan pg',
        uploaded:'3 months ago',
        description:'Located in Sector 1 hsr layout, Bangalore Semi furnished attached bathroom with kitchen tile flooring located at near jp palace hotel behind pearls resort Bangalore.'
    },
    {
        id:9,
        title:'Nr home stays pg for boys',
        location:'9th main road, Bangalore',
        accomodationFor:'Boys',
        suitableFor:'Students and Working',
        price:6000,
        image:['https://www.pgchoice.com/uploads/property/small/IMG_20231019_113245.jpg',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Nr Home Stays pg',
        uploaded:'3 months ago',
        description:'Located in 9th main road, Bangalore, Nr Semi furnished attached bathroom with kitchen tile flooring located at near jp palace hotel behind pearls resort Road Bangalore.'
    },
    {   
        id:10,
        title:'Gopik Girls pg',
        location:'Izatnagar, Bareilly',
        accomodationFor:'Girls',
        suitableFor:'Students and Working',
        price:7500,
        image:['https://www.pgchoice.com/uploads/property/small/IMG-20231012-WA0010.jpg',
        'https://www.pgchoice.com/uploads/property/medium/26e75a88-c4ec-4937-bf5b-e43ed379cdb71.webp',
        'https://www.pgchoice.com/uploads/property/medium/6a8d1625-c0e1-473e-b81c-e962818b979a.webp'],
        ownerName:'Divya Khosla',
        uploaded:'3 months ago',
        description:'Located in Izatnagar Bareilly, Semi furnished attached bathroom with kitchen tile flooring located at near jp palace hotel behind pearls resort.'
    },
]

export default rooms;